# -*- coding: utf-8 -*-
"""comparison_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xRTWkRWG9VSXZshwPy2EUoeWWLBNtLQN

Comparison of the predictions and the ground truth-

Printing the prediction and the ground truth annotations on the same image.
"""

from google.colab import drive
drive.mount('/content/gdrive')

import os
import cv2
import  xml.dom.minidom
from PIL import Image

from google.colab.patches import cv2_imshow
import glob

def showimg(image_path,annotation_path):
  img_path =image_path
  xml_path =annotation_path
  print(img_path)
  img = cv2.imread(img_path)
  print(img)
  if img is None:
      pass
  dom = xml.dom.minidom.parse(xml_path)
  root = dom.documentElement
  objects=dom.getElementsByTagName("object")
  print(objects)
  i=0
  for object in objects:
    bndbox = root.getElementsByTagName('bndbox')[i]
    xmin = bndbox.getElementsByTagName('xmin')[0]
    ymin = bndbox.getElementsByTagName('ymin')[0]
    xmax = bndbox.getElementsByTagName('xmax')[0]
    ymax = bndbox.getElementsByTagName('ymax')[0]
    xmin_data=xmin.childNodes[0].data
    ymin_data=ymin.childNodes[0].data
    xmax_data=xmax.childNodes[0].data
    ymax_data=ymax.childNodes[0].data

    i= i +1
    cv2.rectangle(img,(int(xmin_data),int(ymin_data)),(int(xmax_data),int(ymax_data)),(55,255,155),2)
  flag=0
  if(flag):
	  print(filename,"done")
  print("all done ====================================")
  from google.colab.patches import cv2_imshow
  cv2_imshow(img)

"""Data Preprocessing:"""

#Resize the image to the model
for ImP in glob.glob("../R-CNN/*"):# The folder of images saved from the model
  pic = Image.open(ImP)
  name=str(ImP)
  #It is necessary to fit img_name, to the length of the path
  img_name=name[40:]
  print(img_name)
  new_image = pic.resize((500, 500))
  new_image.save("../test_new_size/"+img_name)

"""Main:"""

for ImP in glob.glob("../test_new_size/*"):
  pic = Image.open(ImP)
  name=str(ImP)
  #It is necessary to fit img_name, to the length of the path
  img_name=name[38:-4]
  #print(name)
  print(img_name)

  image_path="../test_new_size/"+img_name+".jpg"
  annotation_path="../test_xml/test/"+img_name+".xml"
  showimg(image_path,annotation_path)